project:
  type: website

website:
  title: "Tracer"
  # navbar:
  #   left:
  #     - href: index.html
  #       text: Home
  #     - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



